labName: local
test:
  app:
    environment: dev
  output:
    outputFolder:
    downloadFolder:
    apiLogPath:
wait:
  timeout:
    pageLoad: 25 #in seconds
    implicit: 5 #in seconds
    fluentMax: 10 #in seconds
    fluentPolling: 250 #in milliseconds
    retryCount: 10

lab:
  localLab:
    browserName: chrome
    chrome:
      browserLogFileName: chrome-driver-log.log
      browserVersion: stable #Acceptable values are - <version number>, stable, beta, dev, canary
      acceptInsecureCerts: true #bolean
      unhandledPromptBehavior: #Acceptable values are - dismiss, accept, dismiss and notify, accept and notify, ignore
      binary:
      arguments: #List values
#        - headless
      extensions: #List values
      excludeSwitches: #List values
      prefs: #List values
        - key: download-path
          value: #Acceptable values: default, dynamic or <any custom path value>

        - key: download.prompt_for_download
          value: false

        - key: profile.default_content_settings.popups
          value: 0

    edge:
      browserLogFileName: edge-driver-log.log
      browserVersion: stable #Acceptable values are - <version number>, stable, beta, dev, canary
      acceptInsecureCerts: true #bolean
      unhandledPromptBehavior: #Acceptable values: dismiss, accept, dismiss and notify, accept and notify, ignore
      binary:
      arguments: #List values
        - start-maximized
      extensions: #List values
      excludeSwitches: #List values
      prefs: #List values
        - key:
          value:

    firefox:
      browserLogFileName: firefox-driver-log.log
      browserVersion: stable #Acceptable values are - <version number>, stable, beta, dev, canary
      acceptInsecureCerts: true #bolean
      unhandledPromptBehavior: #Acceptable values are - [dismiss, accept, dismiss and notify, accept and notify, ignore]
      binary:
      arguments: #List values
      extensions: #List values
      excludeSwitches: #List values
      prefs: #List values
        - key:
          value:

  gridLab:
    hub:
      name:
      url: https://localhost:4444
    nodes:
      -
        name:
        url:
        maxBrowserInstance:
        maxBrowserSessions:
        browserName:
        browserVersion:
        platformName: